#container
  services:
    webapp:
      build: .
      ports:
        - "8080:80"
      networks:
        - net1
      depends_on:
        - sqlserver
      environment:
        - ConnectionStrings:Application=Server=sqlserver;Database=Ecommerce;User Id:sa;Password=@Ahmed@123;Trust Server Certificate=True
  
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      networks:
         - net1
      hostname: sqlserver
      volumes:
         - sqldata:/var/opt/mssql
      environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=@Ahmed@123

# Networks
  networks:
    net1:
#Volums 
  volumes:
     sqldata:    

